[package]
name = "wick"
version = "0.1.0"
edition = "2024"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "wick"
crate-type = ["cdylib"]

[dependencies]
candle-core = "0.9.1"
candle-nn = "0.9.1"
pyo3 = "0.27.0"
